PREFIX bk: <http://knetminer.org/data/rdf/terms/biokno/>
PREFIX bkr: <http://knetminer.org/data/rdf/resources/>
PREFIX bka: <http://knetminer.org/data/rdf/terms/biokno/attributes/>
PREFIX bkds: <http://knetminer.org/data/rdf/terms/biokno/dataSources/>
PREFIX bkev: <http://knetminer.org/data/rdf/terms/biokno/evidences/>
PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

# Searches pathways and related proteins
#
SELECT ?pathName ?protName 
WHERE {
  ?path a bk:Path;
    bk:prefName ?pathName.

  ?bkProt a bk:Protein;
    bk:prefName ?protName;
    bk:participates_in ?path;
    bk:evidence bkev:IMPD.
}
